version: "3"

services:
  nginx:
    image: docker.pkg.github.com/goartisan/laravel-twitter-clone/nginx:latest
    ports:
      - 80:80
    depends_on:
      - "php"
  php:
    image: docker.pkg.github.com/goartisan/laravel-twitter-clone/php:latest
    volumes:
      - ./server:/var/www
    ports:
      - 9000:9000
    depends_on:
      - "db"

  db:
    image: docker.pkg.github.com/goartisan/laravel-twitter-clone/db:latest
    environment:
      MYSQL_DATABASE: laravel_twitter_clone
      MYSQL_ROOT_PASSWORD: docker
    ports:
      - 3306:3306
