version: "3"

services:
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - ./server:/var/www
    ports:
      - 80:80

  db:
    build:
      context: .
      dockerfile: ./.docker/db/Dockerfile
    environment:
      MYSQL_DATABASE: laravel_twitter_clone
      MYSQL_ROOT_PASSWORD: docker
      TZ: "Asia/Tokyo"
    volumes:
      - data:/var/lib/mysql:cached
    ports:
      - 3306:3306

volumes:
  data:
    driver: local
