version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - app-volume:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - app-volume:/var/www
      - ./server/.env.example:/var/www/.env
    ports:
      - 9000:9000

  db:
    build:
      context: .
      dockerfile: ./.docker/db/Dockerfile
    environment:
      MYSQL_DATABASE: laravel_twitter_clone
      MYSQL_ROOT_PASSWORD: docker
      TZ: "Asia/Tokyo"
    volumes:
      - data:/var/lib/mysql:cached
    ports:
      - 3306:3306

volumes:
  app-volume:
  data:
    driver: local
