version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - app-volume:/var/www
    ports:
      - 80:80
    depends_on:
      - "php"

  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - app-volume:/var/www
    ports:
      - 9000:9000
    depends_on:
      - "db"

  db:
    build:
      context: .
      dockerfile: ./.docker/db/Dockerfile
    environment:
      MYSQL_DATABASE: laravel_twitter_clone
      MYSQL_ROOT_PASSWORD: docker
      TZ: "Asia/Tokyo"
    volumes:
      - data:/var/lib/mysql:cached
    ports:
      - 3306:3306

volumes:
  app-volume:
  data:
    driver: local
