name: Builds for DockerHub

on: [push]

env:
  IMAGE_NAME_NGINX: ${{ github.repository }}-nginx
  IMAGE_TAG_NGINX: latest
  IMAGE_NAME_PHP: ${{ github.repository }}-php
  IMAGE_TAG_PHP: latest
  IMAGE_NAME_DB: ${{ github.repository }}-db
  IMAGE_TAG_DB: latest

jobs:
  builds-for-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push a nginx image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.docker/nginx/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME_NGINX }}:${{ env.IMAGE_TAG_NGINX }}

      - name: Build and push a php image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.docker/php/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME_PHP }}:${{ env.IMAGE_TAG_PHP }}

      - name: Build and push a db image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.docker/db/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME_DB }}:${{ env.IMAGE_TAG_DB }}
